name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  - main

pool:
  vmImage: 'Default'

variables:
  azureServiceConnection: 'AzureConnection'
  acrServiceConnection: 'AcrConnection'
  
  resourceGroup: 'my-resource-group'
  storageAccount: 'tfstateacc'
  container: 'tfstate'
  tfKey: 'terraform.tfstate'
  tfWorkingDirectory: '$(System.DefaultWorkingDirectory)/terraform'

  imageRepository: 'bestrong-api'
  acrName: 'acrbestrongtazoao' 
  webAppName: 'app-bestrong-tazoao'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'

stages:
  - stage: Infrastructure
    displayName: 'Provision Infrastructure'
    jobs:
      - job: Terraform
        displayName: 'Terraform Apply'
        steps:
          - task: TerraformTaskV4@4
            displayName: 'Terraform Init'
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(tfWorkingDirectory)'
              backendServiceArm: '$(azureServiceConnection)'
              backendAzureRmResourceGroupName: '$(resourceGroup)'
              backendAzureRmStorageAccountName: '$(storageAccount)'
              backendAzureRmContainerName: '$(container)'
              backendAzureRmKey: '$(tfKey)'

          - task: TerraformTaskV4@4
            displayName: 'Terraform Validate'
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: '$(tfWorkingDirectory)'

          - task: TerraformTaskV4@4
            displayName: 'Terraform Apply'
            inputs:
              provider: 'azurerm'
              command: 'apply'
              workingDirectory: '$(tfWorkingDirectory)'
              commandOptions: '-auto-approve'
              environmentServiceNameAzureRM: '$(azureServiceConnection)'

  - stage: Build
    displayName: 'Build and Push Docker Image'
    dependsOn: Infrastructure
    condition: succeeded()
    jobs:
      - job: Build
        displayName: 'Build & Push'
        steps:
          - task: Docker@2
            displayName: 'Build and Push to ACR'
            inputs:
              command: buildAndPush
              repository: $(imageRepository)
              dockerfile: $(dockerfilePath)
              containerRegistry: $(acrServiceConnection)
              tags: |
                $(tag)
                latest

  - stage: Deploy
    displayName: 'Deploy to Azure Web App'
    dependsOn: Build
    condition: succeeded()
    jobs:
      - job: Deploy
        displayName: 'Update Web App'
        steps:
          - task: AzureWebAppContainer@1
            displayName: 'Deploy Container'
            inputs:
              azureSubscription: $(azureServiceConnection)
              appName: $(webAppName)
              containers: '$(acrName).azurecr.io/$(imageRepository):$(tag)'